// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: U1qexeZAxKnFPqFFnSEUB
// Component: _IdL1cxKQVorfU
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Ratings from "../../Ratings"; // plasmic-import: zrgn7co2QChg9g/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: U1qexeZAxKnFPqFFnSEUB/projectcss
import * as sty from "./PlasmicProductCard.module.css"; // plasmic-import: _IdL1cxKQVorfU/css

import ShoppingCartIcon from "./icons/PlasmicIcon__ShoppingCart"; // plasmic-import: WKpqs2Ib1G56uD/icon
import HeartOIcon from "./icons/PlasmicIcon__HeartO"; // plasmic-import: _gk-eELFqCAG1_/icon
import ExpandIcon from "./icons/PlasmicIcon__Expand"; // plasmic-import: UOmFOZSEe6t19O/icon
import f1Qf8FNuXqJpnN34 from "./images/f1.jpeg"; // plasmic-import: qf8fNUXqJpnN34/picture

export type PlasmicProductCard__VariantMembers = {
  withReviews: "withReviews";
  onSale: "onSale";
};

export type PlasmicProductCard__VariantsArgs = {
  withReviews?: SingleBooleanChoiceArg<"withReviews">;
  onSale?: SingleBooleanChoiceArg<"onSale">;
};

type VariantPropType = keyof PlasmicProductCard__VariantsArgs;
export const PlasmicProductCard__VariantProps = new Array<VariantPropType>(
  "withReviews",
  "onSale"
);

export type PlasmicProductCard__ArgsType = {
  title?: React.ReactNode;
  price?: React.ReactNode;
  image?: React.ReactNode;
  ratings?: React.ReactNode;
};

type ArgPropType = keyof PlasmicProductCard__ArgsType;
export const PlasmicProductCard__ArgProps = new Array<ArgPropType>(
  "title",
  "price",
  "image",
  "ratings"
);

export type PlasmicProductCard__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultProductCardProps {
  title?: React.ReactNode;
  price?: React.ReactNode;
  image?: React.ReactNode;
  ratings?: React.ReactNode;
  withReviews?: SingleBooleanChoiceArg<"withReviews">;
  onSale?: SingleBooleanChoiceArg<"onSale">;
  className?: string;
}

function PlasmicProductCard__RenderFunc(props: {
  variants: PlasmicProductCard__VariantsArgs;
  args: PlasmicProductCard__ArgsType;
  overrides: PlasmicProductCard__OverridesType;
  dataFetches?: PlasmicProductCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__onSale]: hasVariant(variants, "onSale", "onSale"),
        [sty.root__withReviews]: hasVariant(
          variants,
          "withReviews",
          "withReviews"
        )
      })}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <div className={classNames(defaultcss.all, sty.freeBox__rpLk)}>
        {p.renderPlasmicSlot({
          defaultContents: (
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__vv4Zf)}
              role={"img"}
              src={f1Qf8FNuXqJpnN34}
            />
          ),

          value: args.image
        })}

        {(hasVariant(variants, "onSale", "onSale") ? true : false) ? (
          <div
            className={classNames(defaultcss.all, sty.freeBox__tr2W, {
              [sty.freeBox__onSale__tr2W2Knt]: hasVariant(
                variants,
                "onSale",
                "onSale"
              )
            })}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__vXhl7
              )}
            >
              {"Sale"}
            </div>
          </div>
        ) : null}
        {(triggers.hover_root ? true : false) ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.freeBox__fWfGa)}
          >
            <ShoppingCartIcon
              className={classNames(defaultcss.all, sty.svg__bIqcJ)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.freeBox__j14BX
              )}
            >
              {"Add to cart"}
            </div>

            <HeartOIcon
              className={classNames(defaultcss.all, sty.svg__rAkg)}
              role={"img"}
            />

            <ExpandIcon
              className={classNames(defaultcss.all, sty.svg__d5Eb7)}
              role={"img"}
            />
          </p.Stack>
        ) : null}
      </div>

      {(hasVariant(variants, "withReviews", "withReviews") ? true : false)
        ? p.renderPlasmicSlot({
            defaultContents: (
              <Ratings
                className={classNames("__wab_instance", sty.ratings___0Rahc)}
              />
            ),

            value: args.ratings
          })
        : null}

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox__t9Lde)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Title",
          value: args.title,
          className: classNames(sty.slotTitle)
        })}

        {p.renderPlasmicSlot({
          defaultContents: "$100",
          value: args.price,
          className: classNames(sty.slotPrice)
        })}
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProductCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProductCard__VariantsArgs;
    args?: PlasmicProductCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicProductCard__Fetches;
  } & Omit<PlasmicProductCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProductCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProductCard__ArgProps,
      internalVariantPropNames: PlasmicProductCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicProductCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductCard";
  } else {
    func.displayName = `PlasmicProductCard.${nodeName}`;
  }
  return func;
}

export const PlasmicProductCard = Object.assign(
  // Top-level PlasmicProductCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicProductCard
    internalVariantProps: PlasmicProductCard__VariantProps,
    internalArgProps: PlasmicProductCard__ArgProps
  }
);

export default PlasmicProductCard;
/* prettier-ignore-end */
