// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: U1qexeZAxKnFPqFFnSEUB
// Component: UTpklsfcvuMrq
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: YrPXBCHaWJzYT/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: 0R58w5_g-sIQLU/component
import ProductCard from "../../ProductCard"; // plasmic-import: _IdL1cxKQVorfU/component
import Ratings from "../../Ratings"; // plasmic-import: zrgn7co2QChg9g/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: -A-XHNltYFOeC/component
import BlogPost from "../../BlogPost"; // plasmic-import: FqHwe52w8GjX8c/component
import Footer from "../../Footer"; // plasmic-import: p6FVu5Eb-V179/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wH-Eb1OeYquQUw/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: U1qexeZAxKnFPqFFnSEUB/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: UTpklsfcvuMrq/css

import arrivals1Ja60Ni3W8Z2DVi from "./images/arrivals1.png"; // plasmic-import: ja60Ni3W8Z2DVi/picture
import arrivals21AsdSOu1AyUUrn from "./images/arrivals2.png"; // plasmic-import: 1asdSOu1ayUUrn/picture
import arrivals3GTxeqSyMkzUZd from "./images/arrivals3.png"; // plasmic-import: gTxeqSYMkz-UZd/picture
import arrivals4CeCksfjyyUgXji from "./images/arrivals4.png"; // plasmic-import: CECksfjyyUgXJI/picture
import arrivals58HJg9Gn7GicFi0 from "./images/arrivals5.png"; // plasmic-import: 8hJG9gn7GICFi0/picture
import arrivals6UekQFhMUxDoMdX from "./images/arrivals6.png"; // plasmic-import: uekQFhMUxDoMdX/picture
import arrivals7ZHy34MlUJjxC from "./images/arrivals7.png"; // plasmic-import: zHy_34Ml-uJjxC/picture
import arrivals8HYNmI4E4T5CrvN from "./images/arrivals8.png"; // plasmic-import: hYNmI4E4T5CrvN/picture
import f1Qf8FNuXqJpnN34 from "./images/f1.jpeg"; // plasmic-import: qf8fNUXqJpnN34/picture
import f23NNNsWgZhHJoxR from "./images/f2.jpeg"; // plasmic-import: 3nNNsWgZhHJoxR/picture
import f3PtoXdRpfChbqD from "./images/f3.jpeg"; // plasmic-import: Pto-XdRpfChbqD/picture
import f4B3Ou3Naas8PsXk from "./images/f4.jpeg"; // plasmic-import: b3Ou3Naas8PSXk/picture
import b1AZZ1VUwi0Au0 from "./images/b1.jpeg"; // plasmic-import: aZ-Z1VUwi0au0_/picture
import b22TClws9C4M3U9 from "./images/b2.jpeg"; // plasmic-import: 2tClws9_c4m3u9/picture
import b3XzcilmjiwghhOg from "./images/b3.jpeg"; // plasmic-import: XzcilmjiwghhOG/picture
import adidasDlvhAeBQpOifyw from "./images/adidas.png"; // plasmic-import: DLVHAeBQpOIFYW/picture
import hm24DBqXgrN8 from "./images/hm.png"; // plasmic-import: _24-d_BqXgrN8_/picture
import kappaRmC4VAkqH6BQq from "./images/kappa.png"; // plasmic-import: rmC4VAkqH6BQq_/picture
import lacosteQBexGlBa1U0CQ from "./images/lacoste.png"; // plasmic-import: qBexGl-BA1u0cQ/picture
import levis44V2YuoGLgEfd1 from "./images/levis.png"; // plasmic-import: 44V2yuoGLgEFD1/picture

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  productCarousel?: p.Flex<typeof ProductCarousel>;
  featureItem?: p.Flex<typeof FeatureItem>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  dataFetches?: PlasmicHome__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.freeBox__hYrBp)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__iQw99)}
            >
              <div className={classNames(defaultcss.all, sty.freeBox__yfLnw)}>
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox__ix1Nv)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___6L7So
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___1BOx6)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__kez8L)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___960Ej)}
                    role={"img"}
                    src={arrivals1Ja60Ni3W8Z2DVi}
                  />
                }
                onSale={"onSale" as const}
                price={"$65.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___7X2Aw
                    )}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__jJL)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___1TW0J)}
                    role={"img"}
                    src={arrivals21AsdSOu1AyUUrn}
                  />
                }
                onSale={"onSale" as const}
                price={"$80.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___7HfOa
                    )}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Single Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__cwSrF)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__gQGoO)}
                    role={"img"}
                    src={arrivals3GTxeqSyMkzUZd}
                  />
                }
                price={"$40.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__gZ4W)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__f82W9)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__hfjb7)}
                    role={"img"}
                    src={arrivals4CeCksfjyyUgXji}
                  />
                }
                onSale={"onSale" as const}
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__afigf)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Stylish Chair"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___0YmYd)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__tBvQf)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__shfb2)}
                    role={"img"}
                    src={arrivals58HJg9Gn7GicFi0}
                  />
                }
                price={"$120.00"}
                title={"Modern Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__aW43)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__qzzOu)}
                    role={"img"}
                    src={arrivals6UekQFhMUxDoMdX}
                  />
                }
                onSale={"onSale" as const}
                price={"$140.00"}
                title={"Mapple Wood Dinning Table"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__tc64O)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3Ac7M)}
                    role={"img"}
                    src={arrivals7ZHy34MlUJjxC}
                  />
                }
                onSale={"onSale" as const}
                price={"$90.00"}
                title={"Arm Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__hIa4V)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ymMqa)}
                    role={"img"}
                    src={arrivals8HYNmI4E4T5CrvN}
                  />
                }
                price={"$140.00"}
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__oktqa
                    )}
                  >
                    {"Wooden Bed"}
                  </div>
                }
              />
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(defaultcss.all, sty.freeBox__tU8P9)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__u0W9L
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__dYcPb)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__fwhXj)}
                price={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__lqZbs
                    )}
                  >
                    {"$160.00"}
                  </div>
                }
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__vZuR)}
                    numReviews={"(12 Review)"}
                    stars={"two" as const}
                  />
                }
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___9WenF
                    )}
                  >
                    {"Designed Sofa"}
                  </div>
                }
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___52NJa
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__slfls)}
                    role={"img"}
                    src={f23NNNsWgZhHJoxR}
                  />
                }
                price={"$200.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__lyAeN)}
                    stars={"four" as const}
                  />
                }
                title={"Dining Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__gUbr)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___98XKc)}
                    role={"img"}
                    src={f3PtoXdRpfChbqD}
                  />
                }
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__efjmP)}
                    numReviews={"(23 Review)"}
                    stars={"five" as const}
                  />
                }
                title={"Chair and Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___6TPx6
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__piX4U)}
                    role={"img"}
                    src={f4B3Ou3Naas8PsXk}
                  />
                }
                price={"$299.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__tii73)}
                    numReviews={"(35 Review)"}
                  />
                }
                title={"Modern Arm Chair"}
                withReviews={"withReviews" as const}
              />
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox___6Z6T1)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__aeLp
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__y8Nf)}
            >
              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__hniTt)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__jGyA)}
                    role={"img"}
                    src={b1AZZ1VUwi0Au0}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__irvEt)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__bgOHm)}
                    role={"img"}
                    src={b22TClws9C4M3U9}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__jpaus)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3JQf)}
                    role={"img"}
                    src={b3XzcilmjiwghhOg}
                  />
                }
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__nrVJp)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___0PveH)}
                role={"img"}
                src={adidasDlvhAeBQpOifyw}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___3KGRb)}
                role={"img"}
                src={hm24DBqXgrN8}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__dUl8)}
                role={"img"}
                src={kappaRmC4VAkqH6BQq}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__mmPya)}
                role={"img"}
                src={lacosteQBexGlBa1U0CQ}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__s2U6P)}
                role={"img"}
                src={levis44V2YuoGLgEfd1}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  productCarousel: typeof ProductCarousel;
  featureItem: typeof FeatureItem;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHome__Fetches;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
